(() => {
  const C = window.CircuitLab, $ = s => document.querySelector(s), palette=$('#palette');
  const colors={resistor:'#8b9cff',voltage:'#f4b860',current:'#58d6ba',ground:'#58d6ba',lamp:'#f4b860'};
  const icons={resistor:'▱',voltage:'⌁',current:'↗',ground:'⏚',lamp:'✳'};
  let circuit, selected=null, wireStart=null, results=null, placement=0;
  try { circuit=JSON.parse(localStorage.getItem('shortcircuit-circuit')) || C.createCircuit('Untitled circuit'); } catch { circuit=C.createCircuit(); }
  const fmt=(n,u='')=>`${Number(n).toFixed(Math.abs(n)<.01?4:2)}${u}`;
  function save(){localStorage.setItem('shortcircuit-circuit',JSON.stringify(circuit));$('#project-name').textContent=circuit.name;}
  function notify(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.classList.remove('show'),2400);}
  Object.entries(C.definitions).forEach(([type,d])=>{const b=document.createElement('button');b.className='component-card';b.innerHTML=`<span class="component-icon" style="--icon:${colors[type]}">${icons[type]}</span><span class="component-label">${d.label}<small>${type==='resistor'?'Passive · 2 pin':type==='voltage'?'Source · 2 pin':type==='ground'?'Reference · 1 pin':'Source · 2 pin'}</small></span><span class="add-symbol">＋</span>`;b.onclick=()=>add(type);palette.append(b);});
  function add(type){const spot=[{x:350,y:280},{x:550,y:280},{x:450,y:410},{x:650,y:410},{x:250,y:410}][placement++%5];const p=C.addComponent(circuit,type,spot);selected=p.id;results=null;render();showProps();save();notify(`${C.definitions[type].label} added to schematic`);}
  function render(){
    $('#canvas').innerHTML=C.toSvg(circuit);
    const svg=$('#canvas svg');
    svg.querySelectorAll('.part').forEach(g=>{if(g.dataset.id===selected)g.classList.add('selected');g.addEventListener('click',e=>{if(e.target.classList.contains('terminal'))return;e.stopPropagation();selected=g.dataset.id;wireStart=null;render();showProps();});});
    svg.querySelectorAll('.terminal').forEach(t=>t.addEventListener('click',e=>{e.stopPropagation();const ref={component:t.dataset.component,terminal:t.dataset.terminal};if(!wireStart){wireStart=ref;notify(`Choose a terminal to connect from ${ref.component}.${ref.terminal}`);t.classList.add('active-terminal');}else{try{C.connect(circuit,wireStart,ref);results=null;notify('Wire connected');}catch(err){notify(err.message);}wireStart=null;render();save();}}));
    $('#node-count').textContent=`${new Set(circuit.components.flatMap(p=>C.definitions[p.type].terminals.map(t=>`${p.id}.${t}`)).filter(k=>!circuit.wires.some(w=>`${w.from.component}.${w.from.terminal}`===k||`${w.to.component}.${w.to.terminal}`===k))).size+circuit.wires.length} terminals`;
    $('#canvas-hint').classList.toggle('hidden',circuit.components.length===0);
    if(results)showResults();else $('#status-text').textContent='Ready to simulate';
  }
  function showProps(){const host=$('#properties'),p=circuit.components.find(x=>x.id===selected);if(!p){host.innerHTML='Select a component<br>to edit its values.';host.className='empty-state';return;}host.className='property-form';let field='';if(p.type==='resistor'||p.type==='lamp')field=`<label>Resistance <span>Ω</span><input data-key="resistance" type="number" min="0.001" step="any" value="${p.resistance}"></label>`;if(p.type==='voltage')field=`<label>Voltage <span>V</span><input data-key="voltage" type="number" step="any" value="${p.voltage}"></label>`;if(p.type==='current')field=`<label>Current <span>A</span><input data-key="current" type="number" step="any" value="${p.current}"></label>`;host.innerHTML=`<div class="selected-name"><span class="component-icon" style="--icon:${colors[p.type]}">${icons[p.type]}</span><div><b>${C.definitions[p.type].label}</b><small>${p.id}</small></div><button id="delete-part" title="Delete component">⌫</button></div>${field}<div class="terminal-list"><span>TERMINALS</span>${C.definitions[p.type].terminals.map(t=>`<div><i></i>${t==='+'?'Positive':t==='−'?'Negative':t==='gnd'?'Ground':`Pin ${t.toUpperCase()}`}</div>`).join('')}</div>`;host.querySelectorAll('input').forEach(i=>i.oninput=()=>{p[i.dataset.key]=Number(i.value);results=null;save();render();});$('#delete-part').onclick=()=>{circuit.components=circuit.components.filter(x=>x.id!==p.id);circuit.wires=circuit.wires.filter(w=>w.from.component!==p.id&&w.to.component!==p.id);selected=null;results=null;render();showProps();save();};}
  function showResults(){const host=$('#results-content');host.classList.remove('empty-instruments');host.innerHTML=`<div class="solve-summary"><span class="success-icon">✓</span><div><b>Circuit solved</b><small>${results.summary}</small></div></div><div class="reading-grid">${results.components.filter(r=>r.type!=='ground').map(r=>{const p=circuit.components.find(x=>x.id===r.id);return `<article class="reading-card"><div class="reading-top"><span class="reading-icon" style="--icon:${colors[r.type]}">${icons[r.type]}</span><span>${C.definitions[r.type].label} <small>${r.id}</small></span></div><div class="reading-primary">${fmt(r.voltage,' V')}</div><div class="reading-secondary"><span>Current <b>${fmt(r.current,' A')}</b></span><span>Power <b>${fmt(r.power,' W')}</b></span></div></article>`;}).join('')}</div><div class="node-readings"><div class="eyebrow">NODE VOLTAGES</div>${Object.entries(results.nodes).map(([n,v])=>`<div><span>${n}</span><b>${fmt(v,' V')}</b></div>`).join('')||'<small>All terminals at ground potential.</small>'}</div>`;$('#run-time').textContent='SIMULATION COMPLETE';$('#status-text').textContent='Solved successfully';}
  function run(){try{results=C.solve(circuit);showResults();notify('Simulation converged successfully');}catch(e){results=null;$('#results-content').classList.add('empty-instruments');$('#results-content').innerHTML=`<div class="error-state"><span>!</span><b>Simulation stopped</b><p>${e.message}</p><small>Check the wiring and make sure each circuit has a ground.</small></div>`;$('#run-time').textContent='SIMULATION ERROR';$('#status-text').textContent='Needs attention';}}
  $('#run-btn').onclick=run;$('#new-btn').onclick=()=>{circuit=C.createCircuit('Untitled circuit');selected=null;results=null;placement=0;render();showProps();save();};$('#fit-btn').onclick=()=>notify('Schematic fits the workspace');$('#clear-wires').onclick=()=>{circuit.wires=[];results=null;render();save();notify('All wires cleared');};$('#mcp-copy').onclick=async()=>{try{await navigator.clipboard.writeText('node mcp-server.js');notify('MCP command copied');}catch{notify('Run “node mcp-server.js” from this project folder');}};
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();run();}if(e.key==='Escape'){wireStart=null;render();}if((e.key==='Delete'||e.key==='Backspace')&&selected&&!['INPUT'].includes(document.activeElement.tagName))$('#delete-part')?.click();});
  if(!circuit.components.length){circuit=C.createCircuit('Series circuit · 5V');circuit.name='Series circuit · 5V';const v=C.addComponent(circuit,'voltage',{x:260,y:270}),r=C.addComponent(circuit,'resistor',{x:500,y:270,resistance:1000}),g=C.addComponent(circuit,'ground',{x:740,y:385});C.connect(circuit,{component:v.id,terminal:'+'},{component:r.id,terminal:'a'});C.connect(circuit,{component:r.id,terminal:'b'},{component:g.id,terminal:'gnd'});C.connect(circuit,{component:v.id,terminal:'−'},{component:g.id,terminal:'gnd'});}
  render();showProps();save();
})();
