(() => {
  const C = window.CircuitLab, $ = s => document.querySelector(s), palette=$('#palette');
  const colors=Object.fromEntries(Object.entries(C.definitions).map(([k,d])=>[k,d.color]));
  const icons=Object.fromEntries(Object.entries(C.definitions).map(([k,d])=>[k,d.symbol]));
  let circuit, selected=null, wireStart=null, results=null, placement=0, projects=[], activeProject='', projectSyncReady=false, saveChain=Promise.resolve(), zoom=1, viewX=0, viewY=0;
  try {
    projects=JSON.parse(localStorage.getItem('shortcircuit-projects')) || [];
    if(!projects.length){const legacy=JSON.parse(localStorage.getItem('shortcircuit-circuit'));if(legacy)projects=[{id:`project-${Date.now()}`,circuit:legacy}];}
    if(!projects.length)projects=[{id:`project-${Date.now()}`,circuit:C.createCircuit('Untitled circuit')}];
    activeProject=localStorage.getItem('shortcircuit-active-project')||projects[0].id;
    if(!projects.some(p=>p.id===activeProject))activeProject=projects[0].id;
    circuit=projects.find(p=>p.id===activeProject).circuit;
  } catch { projects=[{id:`project-${Date.now()}`,circuit:C.createCircuit()}];activeProject=projects[0].id;circuit=projects[0].circuit; }
  const fmt=(n,u='')=>`${Number(n).toFixed(Math.abs(n)<.01?4:2)}${u}`;
  function save(){const project=projects.find(p=>p.id===activeProject);if(project)project.circuit=circuit;localStorage.setItem('shortcircuit-projects',JSON.stringify(projects));localStorage.setItem('shortcircuit-active-project',activeProject);localStorage.setItem('shortcircuit-circuit',JSON.stringify(circuit));$('#project-list').innerHTML=projects.map(p=>`<option value="${p.id}">${String(p.circuit.name||'Untitled circuit').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}</option>`).join('');$('#project-list').value=activeProject;if(projectSyncReady&&project) {const snapshot=JSON.stringify({id:project.id,circuit:project.circuit,updatedAt:project.updatedAt});saveChain=saveChain.then(()=>fetch('/api/projects',{method:'PUT',headers:{'Content-Type':'application/json'},body:snapshot})).then(r=>{if(!r.ok)throw new Error('Project sync failed');return r.json();}).then(saved=>{const current=projects.find(p=>p.id===saved.id);if(current)current.updatedAt=saved.updatedAt;}).catch(()=>notify('Could not sync project with MCP storage'));}}
  async function loadSharedProjects(){try{const response=await fetch('/api/projects');if(!response.ok)return;const remote=(await response.json()).projects;if(remote.length){projects=remote;activeProject=projects.some(p=>p.id===activeProject)?activeProject:projects[0].id;circuit=projects.find(p=>p.id===activeProject).circuit;selected=null;results=null;render();showProps();}projectSyncReady=true;if(!remote.length){for(const project of projects){const r=await fetch('/api/projects',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(project)});if(!r.ok)throw new Error('Project migration failed');const saved=await r.json();project.updatedAt=saved.updatedAt;}}else save();}catch{projectSyncReady=true;notify('Project storage is unavailable; changes remain in this browser');}}
  async function refreshSharedProjects(){if(document.visibilityState!=='visible'||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;try{const response=await fetch('/api/projects');if(!response.ok)return;const remote=(await response.json()).projects;let changed=false;for(const incoming of remote){const local=projects.find(p=>p.id===incoming.id);if(!local){projects.push(incoming);changed=true;}else if(incoming.updatedAt&&incoming.updatedAt!==local.updatedAt){Object.assign(local,incoming);changed=true;if(incoming.id===activeProject)circuit=incoming.circuit;}}if(changed){if(!projects.some(p=>p.id===activeProject)){activeProject=projects[0].id;circuit=projects[0].circuit;}save();render();showProps();}}catch{}}
  function notify(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.classList.remove('show'),2400);}
  const aliases={buck12:'LM2596HV DROK 12V',buck5:'D-Planet 5A 5V converter',tvs:'SMBJ33A 33V transient suppressor',mov:'MOV-10D220K 22V varistor',schottky:'B540C-13-F ORing',zener:'BZX84C3V3 clamp SZBZX84B12LT1G',inductor:'SRR1260-100M 10uH choke',fuse:'10A blade F1',mosfet:'IRF5305PBF reverse polarity Q1',regulator3v3:'LD1117S33TR LT1763CS8-3.3',supercap:'2F 5.5V C4',electrolytic_capacitor:'470uF 50V 100uF 25V bypass',ford_ntc:'temperature coolant sender thermistor',fuel_sender:'15 160 ohm fuel gauge tank sender',oil_pressure_sensor:'oil pressure transducer 3 wire 0.5 4.5v',lm1815_conditioner:'tachometer VR pickup conditioner',relay_module:'relay coil MOSFET driver',ldr:'light sensor photoresistor'};
  Object.entries(C.definitions).forEach(([type,d])=>{const b=document.createElement('button');b.className='component-card';b.dataset.search=`${d.label} ${d.symbol} ${type} ${aliases[type]||''}`.toLowerCase();const detail=type==='breadboard'?'30 rows · linked strips':['capacitor','electrolytic_capacitor','supercap'].includes(type)?'Passive · DC open':['diode','led','zener','tvs','schottky','mov'].includes(type)?'Protection · nonlinear':['buck12','buck5','regulator3v3'].includes(type)?'Power · regulated':d.terminals.length>2?'Module · pin-level':'Passive · 2 pin';b.innerHTML=`<span class="component-icon" style="--icon:${colors[type]}">${icons[type]}</span><span class="component-label">${d.label}<small>${detail}</small></span><span class="add-symbol">＋</span>`;b.onclick=()=>add(type);palette.append(b);});
  $('#component-search').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();palette.querySelectorAll('.component-card').forEach(b=>b.hidden=!b.dataset.search.includes(q));});
  function add(type){const spots=type==='breadboard'?[{x:500,y:310}]:[{x:170,y:150},{x:390,y:150},{x:610,y:150},{x:830,y:150},{x:170,y:330},{x:390,y:330},{x:610,y:330},{x:830,y:330},{x:170,y:500},{x:390,y:500},{x:610,y:500},{x:830,y:500}];const occupied=circuit.components.map(p=>({x:p.x,y:p.y,r:p.type==='breadboard'?235:C.definitions[p.type].terminals.length>8?80:58}));const spot=spots.map((s,i)=>({ ...s,score:occupied.reduce((n,p)=>n+Math.max(0,p.r-Math.hypot(s.x-p.x,s.y-p.y))**2,0)+i*.01})).sort((a,b)=>a.score-b.score)[0];const p=C.addComponent(circuit,type,spot);selected=p.id;results=null;render();showProps();save();notify(`${C.definitions[type].label} added to schematic`);}
  function render(){
    $('#canvas').innerHTML=C.toSvg(circuit);
    const svg=$('#canvas svg');
    svg.setAttribute('viewBox',`${viewX} ${viewY} ${1000/zoom} ${600/zoom}`);
    svg.querySelectorAll('.part').forEach(g=>{if(g.dataset.id===selected)g.classList.add('selected');g.addEventListener('click',e=>{if(e.target.classList.contains('terminal')||e.target.classList.contains('board-hole'))return;e.stopPropagation();selected=g.dataset.id;wireStart=null;render();showProps();});});
    svg.addEventListener('pointerdown',e=>{const part=e.target.closest('.part');if(!part||e.target.classList.contains('terminal')||e.target.classList.contains('board-hole'))return;e.preventDefault();const item=circuit.components.find(p=>p.id===part.dataset.id);if(!item)return;selected=item.id;wireStart=null;const pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const start=pt.matrixTransform(svg.getScreenCTM().inverse());drag={id:item.id,x:item.x,y:item.y,startX:start.x,startY:start.y,moved:false};$('#canvas-wrap').setPointerCapture(e.pointerId);});
    svg.querySelectorAll('.terminal,.board-hole').forEach(t=>t.addEventListener('click',e=>{e.stopPropagation();const ref={component:t.dataset.component,terminal:t.dataset.terminal};if(!wireStart){wireStart=ref;notify(`Choose a terminal to connect from ${ref.component}.${ref.terminal}`);t.classList.add('active-terminal');}else{try{C.connect(circuit,wireStart,ref);results=null;notify('Wire connected');}catch(err){notify(err.message);}wireStart=null;render();save();}}));
    $('#node-count').textContent=`${new Set(circuit.components.flatMap(p=>C.definitions[p.type].terminals.map(t=>`${p.id}.${t}`)).filter(k=>!circuit.wires.some(w=>`${w.from.component}.${w.from.terminal}`===k||`${w.to.component}.${w.to.terminal}`===k))).size+circuit.wires.length} terminals`;
    $('#canvas-hint').textContent='Drag a component to move · scroll to zoom · click pins to connect';
    $('#canvas-hint').classList.toggle('hidden',circuit.components.length===0);
    if(results)showResults();else $('#status-text').textContent='Ready to simulate';
  }
  let drag=null;
  $('#canvas-wrap').addEventListener('pointermove',e=>{if(!drag)return;const svg=$('#canvas svg'),pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const pos=pt.matrixTransform(svg.getScreenCTM().inverse()),item=circuit.components.find(p=>p.id===drag.id);if(!item)return;item.x=Math.max(45,Math.min(955,drag.x+pos.x-drag.startX));item.y=Math.max(45,Math.min(555,drag.y+pos.y-drag.startY));drag.moved=true;render();});
  $('#canvas-wrap').addEventListener('pointerup',()=>{if(!drag)return;const changed=drag.moved;drag=null;showProps();if(changed)save();});
  $('#canvas-wrap').addEventListener('pointercancel',()=>{drag=null;});
  $('#canvas-wrap').addEventListener('wheel',e=>{e.preventDefault();const svg=$('#canvas svg'),pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const focus=pt.matrixTransform(svg.getScreenCTM().inverse()),oldW=1000/zoom,oldH=600/zoom,fractionX=(focus.x-viewX)/oldW,fractionY=(focus.y-viewY)/oldH;zoom=Math.max(.5,Math.min(4,zoom*(e.deltaY<0?1.12:.89)));viewX=focus.x-fractionX*1000/zoom;viewY=focus.y-fractionY*600/zoom;svg.setAttribute('viewBox',`${viewX} ${viewY} ${1000/zoom} ${600/zoom}`);$('.zoom-label').textContent=`${Math.round(zoom*100)}%`;},{passive:false});
  function showProps(){
    const host=$('#properties'),p=circuit.components.find(x=>x.id===selected);if(!p){host.innerHTML='Select a component<br>to edit its values.';host.className='empty-state';return;}
    host.className='property-form';let fields='';
    const number=(key,label,unit='',min='0')=>`<label>${label}<span>${unit}</span><input data-key="${key}" type="number" min="${min}" step="any" value="${p[key]}"></label>`;
    if(['resistor','lamp','fuse','inductor','ford_ntc','fuel_sender','ldr'].includes(p.type))fields+=number('resistance',p.type==='fuse'?'On resistance':'Resistance','Ω','0.000001');
    if(['capacitor','electrolytic_capacitor','supercap'].includes(p.type)){fields+=number('capacitance','Capacitance','F','0.000000000001')+number('voltageRating','Voltage rating','V','0.1');}
    if(p.type==='inductor')fields+=number('inductance','Inductance','H','0.000000001');
    if(p.type==='fuse')fields+=number('currentRating','Current rating','A','0.01');
    if(['diode','led','schottky','zener','tvs'].includes(p.type)){fields+=number('forwardVoltage','Forward drop','V','0.01');if(['zener','tvs','led'].includes(p.type))fields+=number('breakdownVoltage','Breakdown','V','0.1');}
    if(p.type==='mov')fields+=number('clampVoltage','Clamp voltage','V','1');
    if(['buck12','buck5','regulator3v3'].includes(p.type)){fields+=number('outputVoltage','Output voltage','V','0.1');if(p.type!=='regulator3v3')fields+=number('inputMin','Input minimum','V','0')+number('inputMax','Input maximum','V','0.1')+number('efficiency','Efficiency (0–1)','','0.1');fields+=number('currentLimit','Current limit','A','0.01');}
    if(p.type==='voltage')fields+=number('voltage','Voltage','V');if(p.type==='current')fields+=number('current','Current','A');
    if(p.type==='switch')fields+=`<label>Contact closed<input data-key="closed" type="checkbox" ${p.closed?'checked':''}></label>`;
    if(p.partNumber)fields+=`<label>Part number<input data-key="partNumber" type="text" value="${String(p.partNumber).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}"></label>`;
    if(p.type==='breadboard')fields+=`<div class="breadboard-note">30 rows with two isolated 5-hole strips per row. Each power rail has ten connected holes. Click a hole to wire a component into its row.</div>`;
    const terminals=C.terminalsFor?C.terminalsFor(p):C.definitions[p.type].terminals;
    const shown=terminals.length>18?terminals.slice(0,8).concat(['…'],terminals.slice(-4)):terminals;
    host.innerHTML=`<div class="selected-name"><span class="component-icon" style="--icon:${colors[p.type]}">${icons[p.type]}</span><div><b>${C.definitions[p.type].label}</b><small>${p.id}</small></div><button id="delete-part" title="Delete component">⌫</button></div>${fields}<div class="terminal-list"><span>TERMINALS</span>${shown.map(t=>`<div><i></i>${t==='+'?'Positive':t==='−'?'Negative':t==='gnd'?'Ground':`Pin ${t.toUpperCase()}`}</div>`).join('')}</div>`;
    host.querySelectorAll('input').forEach(i=>i.oninput=()=>{p[i.dataset.key]=i.type==='number'?Number(i.value):i.type==='checkbox'?i.checked:i.value;results=null;save();render();});
    $('#delete-part').onclick=()=>{circuit.components=circuit.components.filter(x=>x.id!==p.id);circuit.wires=circuit.wires.filter(w=>w.from.component!==p.id&&w.to.component!==p.id);selected=null;results=null;render();showProps();save();};
  }
  function showResults(){const host=$('#results-content');host.classList.remove('empty-instruments');host.innerHTML=`<div class="solve-summary"><span class="success-icon">✓</span><div><b>Circuit solved</b><small>${results.summary}</small></div></div><div class="reading-grid">${results.components.filter(r=>r.type!=='ground').map(r=>{const extra=r.inputCurrent!==undefined?`<div class="model-note">Input ${fmt(r.inputVoltage,' V')} · ${fmt(r.inputCurrent,' A')} · ${fmt(r.inputPower,' W')}</div>`:r.model?`<div class="model-note">${r.model}</div>`:'';return `<article class="reading-card"><div class="reading-top"><span class="reading-icon" style="--icon:${colors[r.type]}">${icons[r.type]}</span><span>${C.definitions[r.type].label} <small>${r.id}</small></span></div><div class="reading-primary">${fmt(r.voltage,' V')}</div><div class="reading-secondary"><span>Current <b>${fmt(r.current,' A')}</b></span><span>Power <b>${fmt(r.power,' W')}</b></span></div>${extra}</article>`;}).join('')}</div><div class="node-readings"><div class="eyebrow">NODE VOLTAGES</div>${Object.entries(results.nodes).map(([n,v])=>`<div><span>${n}</span><b>${fmt(v,' V')}</b></div>`).join('')||'<small>All terminals at ground potential.</small>'}</div>`;$('#run-time').textContent='SIMULATION COMPLETE';$('#status-text').textContent='Solved successfully';}
  function run(){try{results=C.solve(circuit);showResults();notify('Simulation converged successfully');}catch(e){results=null;$('#results-content').classList.add('empty-instruments');$('#results-content').innerHTML=`<div class="error-state"><span>!</span><b>Simulation stopped</b><p>${e.message}</p><small>Check the wiring and make sure each circuit has a ground.</small></div>`;$('#run-time').textContent='SIMULATION ERROR';$('#status-text').textContent='Needs attention';}}
  $('#run-btn').onclick=run;$('#new-btn').onclick=()=>{circuit=C.createCircuit('Untitled circuit');activeProject=`project-${Date.now()}`;projects.push({id:activeProject,circuit});selected=null;results=null;placement=0;render();showProps();save();notify('New project created');};
  $('#project-list').onchange=e=>{const p=projects.find(x=>x.id===e.target.value);if(!p)return;activeProject=p.id;circuit=p.circuit;selected=null;wireStart=null;results=null;placement=0;render();showProps();save();};
  $('#save-as-btn').onclick=()=>{const name=prompt('Project name',`${circuit.name} copy`);if(!name||!name.trim())return;circuit=JSON.parse(JSON.stringify(circuit));circuit.name=name.trim();activeProject=`project-${Date.now()}`;projects.push({id:activeProject,circuit});selected=null;results=null;render();showProps();save();notify('Project saved');};
  $('#delete-project-btn').onclick=()=>{if(projects.length<2){notify('Keep at least one project');return;}const removed=activeProject;projects=projects.filter(p=>p.id!==removed);activeProject=projects[0].id;circuit=projects[0].circuit;selected=null;results=null;render();showProps();save();fetch(`/api/projects/${encodeURIComponent(removed)}`,{method:'DELETE'}).catch(()=>notify('Could not sync project deletion'));notify('Project deleted');};
  $('#export-svg-btn').onclick=()=>{const svg=$('#canvas svg').cloneNode(true);svg.setAttribute('xmlns','http://www.w3.org/2000/svg');svg.setAttribute('width','1000');svg.setAttribute('height','600');svg.setAttribute('aria-label',`${circuit.name} schematic`);svg.querySelectorAll('.terminal,.board-hole').forEach(x=>x.remove());const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent=`text{font-family:Arial,sans-serif}.part-name{font-size:11px;fill:#aeb9c8;text-anchor:middle}.part-value{font:10px monospace;fill:#91a0b2;text-anchor:middle}.symbol{fill:none;stroke:var(--part);stroke-width:2.5;stroke-linecap:round;stroke-linejoin:round}.chip-symbol{fill:#dce5ee;text-anchor:middle;font-size:10px}.polarity{fill:#f4b860;font:12px monospace}.wires path{fill:none;stroke:var(--wire,#53ceb0);stroke-width:2.6;stroke-linejoin:round;stroke-linecap:round}.wire-label{font:9px monospace;fill:var(--wire);paint-order:stroke;stroke:#101722;stroke-width:4px;text-anchor:middle}.wire-bridge-halo{fill:none;stroke:#101722;stroke-width:8;stroke-linecap:round}.wire-bridge{fill:none;stroke:var(--wire);stroke-width:2.6;stroke-linecap:round}.board-shell{fill:#182a25;stroke:#71966f;stroke-width:2}.board-channel{fill:#101722}.board-hole{fill:#0d131c;stroke:#738295;stroke-width:.6}.board-title,.board-bank-label,.board-row-label,.board-rail-label{fill:#aeb9c8;font-size:9px}.board-bank-label{font-size:8px}.board-row-label,.board-rail-label{font-family:monospace;font-size:7px}.positive{fill:#ef827f}.negative{fill:#79a9e8}rect[width="100%"][height="100%"]{fill:#101722}#grid{}`;svg.insertBefore(style,svg.firstChild);const data=new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml;charset=utf-8'});const url=URL.createObjectURL(data),a=document.createElement('a');a.href=url;a.download=`${(circuit.name||'circuit').replace(/[^a-z0-9_-]+/gi,'-').replace(/^-|-$/g,'')||'circuit'}.svg`;a.click();URL.revokeObjectURL(url);notify('SVG exported');};
  $('#fit-btn').onclick=()=>{zoom=1;viewX=0;viewY=0;$('.zoom-label').textContent='100%';render();};$('#clear-wires').onclick=()=>{circuit.wires=[];results=null;render();save();notify('All wires cleared');};$('#mcp-copy').onclick=async()=>{try{await navigator.clipboard.writeText('node mcp-server.js');notify('MCP command copied');}catch{notify('Run “node mcp-server.js” from this project folder');}};
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();run();}if(e.key==='Escape'){wireStart=null;render();}if((e.key==='Delete'||e.key==='Backspace')&&selected&&!['INPUT'].includes(document.activeElement.tagName))$('#delete-part')?.click();});
  if(!circuit.components.length){circuit=C.createCircuit('Series circuit · 5V');circuit.name='Series circuit · 5V';const v=C.addComponent(circuit,'voltage',{x:260,y:270}),r=C.addComponent(circuit,'resistor',{x:500,y:270,resistance:1000}),g=C.addComponent(circuit,'ground',{x:740,y:385});C.connect(circuit,{component:v.id,terminal:'+'},{component:r.id,terminal:'a'});C.connect(circuit,{component:r.id,terminal:'b'},{component:g.id,terminal:'gnd'});C.connect(circuit,{component:v.id,terminal:'−'},{component:g.id,terminal:'gnd'});}
  render();showProps();save();loadSharedProjects();setInterval(refreshSharedProjects,2500);
})();
