(() => {
  const C = window.CircuitLab, $ = s => document.querySelector(s), palette=$('#palette');
  const colors=Object.fromEntries(Object.entries(C.definitions).map(([k,d])=>[k,d.color]));
  const icons=Object.fromEntries(Object.entries(C.definitions).map(([k,d])=>[k,d.symbol]));
  let circuit, selected=null, wireStart=null, results=null, placement=0;
  try { circuit=JSON.parse(localStorage.getItem('shortcircuit-circuit')) || C.createCircuit('Untitled circuit'); } catch { circuit=C.createCircuit(); }
  const fmt=(n,u='')=>`${Number(n).toFixed(Math.abs(n)<.01?4:2)}${u}`;
  function save(){localStorage.setItem('shortcircuit-circuit',JSON.stringify(circuit));$('#project-name').textContent=circuit.name;}
  function notify(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.classList.remove('show'),2400);}
  const aliases={buck12:'LM2596HV DROK 12V',buck5:'D-Planet 5A 5V converter',tvs:'SMBJ33A 33V transient suppressor',mov:'MOV-10D220K 22V varistor',schottky:'B540C-13-F ORing',zener:'BZX84C3V3 clamp SZBZX84B12LT1G',inductor:'SRR1260-100M 10uH choke',fuse:'10A blade F1',mosfet:'IRF5305PBF reverse polarity Q1',regulator3v3:'LD1117S33TR LT1763CS8-3.3',supercap:'2F 5.5V C4',electrolytic_capacitor:'470uF 50V 100uF 25V bypass',ford_ntc:'temperature coolant sender thermistor',fuel_sender:'15 160 ohm fuel gauge tank sender',oil_pressure_sensor:'oil pressure transducer 3 wire 0.5 4.5v',lm1815_conditioner:'tachometer VR pickup conditioner',relay_module:'relay coil MOSFET driver',ldr:'light sensor photoresistor'};
  Object.entries(C.definitions).forEach(([type,d])=>{const b=document.createElement('button');b.className='component-card';b.dataset.search=`${d.label} ${d.symbol} ${type} ${aliases[type]||''}`.toLowerCase();const detail=type==='breadboard'?'30 rows · linked strips':['capacitor','electrolytic_capacitor','supercap'].includes(type)?'Passive · DC open':['diode','led','zener','tvs','schottky','mov'].includes(type)?'Protection · nonlinear':['buck12','buck5','regulator3v3'].includes(type)?'Power · regulated':d.terminals.length>2?'Module · pin-level':'Passive · 2 pin';b.innerHTML=`<span class="component-icon" style="--icon:${colors[type]}">${icons[type]}</span><span class="component-label">${d.label}<small>${detail}</small></span><span class="add-symbol">＋</span>`;b.onclick=()=>add(type);palette.append(b);});
  $('#component-search').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();palette.querySelectorAll('.component-card').forEach(b=>b.hidden=!b.dataset.search.includes(q));});
  function add(type){const spots=type==='breadboard'?[{x:500,y:310}]:['buck12','buck5','regulator3v3'].includes(type)?[{x:500,y:320}]:C.definitions[type].terminals.length>4?[{x:500,y:300},{x:360,y:310},{x:650,y:300}]:[{x:350,y:280},{x:550,y:280},{x:450,y:410},{x:650,y:410},{x:250,y:410}];const spot=spots[placement++%spots.length];const p=C.addComponent(circuit,type,spot);selected=p.id;results=null;render();showProps();save();notify(`${C.definitions[type].label} added to schematic`);}
  function render(){
    $('#canvas').innerHTML=C.toSvg(circuit);
    const svg=$('#canvas svg');
    svg.querySelectorAll('.part').forEach(g=>{if(g.dataset.id===selected)g.classList.add('selected');g.addEventListener('click',e=>{if(e.target.classList.contains('terminal')||e.target.classList.contains('board-hole'))return;e.stopPropagation();selected=g.dataset.id;wireStart=null;render();showProps();});});
    svg.querySelectorAll('.terminal,.board-hole').forEach(t=>t.addEventListener('click',e=>{e.stopPropagation();const ref={component:t.dataset.component,terminal:t.dataset.terminal};if(!wireStart){wireStart=ref;notify(`Choose a terminal to connect from ${ref.component}.${ref.terminal}`);t.classList.add('active-terminal');}else{try{C.connect(circuit,wireStart,ref);results=null;notify('Wire connected');}catch(err){notify(err.message);}wireStart=null;render();save();}}));
    $('#node-count').textContent=`${new Set(circuit.components.flatMap(p=>C.definitions[p.type].terminals.map(t=>`${p.id}.${t}`)).filter(k=>!circuit.wires.some(w=>`${w.from.component}.${w.from.terminal}`===k||`${w.to.component}.${w.to.terminal}`===k))).size+circuit.wires.length} terminals`;
    $('#canvas-hint').classList.toggle('hidden',circuit.components.length===0);
    if(results)showResults();else $('#status-text').textContent='Ready to simulate';
  }
  function showProps(){
    const host=$('#properties'),p=circuit.components.find(x=>x.id===selected);if(!p){host.innerHTML='Select a component<br>to edit its values.';host.className='empty-state';return;}
    host.className='property-form';let fields='';
    const number=(key,label,unit='',min='0')=>`<label>${label}<span>${unit}</span><input data-key="${key}" type="number" min="${min}" step="any" value="${p[key]}"></label>`;
    if(['resistor','lamp','fuse','inductor','ford_ntc','fuel_sender','ldr'].includes(p.type))fields+=number('resistance',p.type==='fuse'?'On resistance':'Resistance','Ω','0.000001');
    if(['capacitor','electrolytic_capacitor','supercap'].includes(p.type)){fields+=number('capacitance','Capacitance','F','0.000000000001')+number('voltageRating','Voltage rating','V','0.1');}
    if(p.type==='inductor')fields+=number('inductance','Inductance','H','0.000000001');
    if(p.type==='fuse')fields+=number('currentRating','Current rating','A','0.01');
    if(['diode','led','schottky','zener','tvs'].includes(p.type)){fields+=number('forwardVoltage','Forward drop','V','0.01');if(['zener','tvs','led'].includes(p.type))fields+=number('breakdownVoltage','Breakdown','V','0.1');}
    if(p.type==='mov')fields+=number('clampVoltage','Clamp voltage','V','1');
    if(['buck12','buck5','regulator3v3'].includes(p.type)){fields+=number('outputVoltage','Output voltage','V','0.1');if(p.type!=='regulator3v3')fields+=number('inputMin','Input minimum','V','0')+number('inputMax','Input maximum','V','0.1')+number('efficiency','Efficiency (0–1)','','0.1');fields+=number('currentLimit','Current limit','A','0.01');}
    if(p.type==='voltage')fields+=number('voltage','Voltage','V');if(p.type==='current')fields+=number('current','Current','A');
    if(p.type==='switch')fields+=`<label>Contact closed<input data-key="closed" type="checkbox" ${p.closed?'checked':''}></label>`;
    if(p.partNumber)fields+=`<label>Part number<input data-key="partNumber" type="text" value="${String(p.partNumber).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}"></label>`;
    if(p.type==='breadboard')fields+=`<div class="breadboard-note">30 rows with two isolated 5-hole strips per row. Each power rail has ten connected holes. Click a hole to wire a component into its row.</div>`;
    const terminals=C.terminalsFor?C.terminalsFor(p):C.definitions[p.type].terminals;
    const shown=terminals.length>18?terminals.slice(0,8).concat(['…'],terminals.slice(-4)):terminals;
    host.innerHTML=`<div class="selected-name"><span class="component-icon" style="--icon:${colors[p.type]}">${icons[p.type]}</span><div><b>${C.definitions[p.type].label}</b><small>${p.id}</small></div><button id="delete-part" title="Delete component">⌫</button></div>${fields}<div class="terminal-list"><span>TERMINALS</span>${shown.map(t=>`<div><i></i>${t==='+'?'Positive':t==='−'?'Negative':t==='gnd'?'Ground':`Pin ${t.toUpperCase()}`}</div>`).join('')}</div>`;
    host.querySelectorAll('input').forEach(i=>i.oninput=()=>{p[i.dataset.key]=i.type==='number'?Number(i.value):i.type==='checkbox'?i.checked:i.value;results=null;save();render();});
    $('#delete-part').onclick=()=>{circuit.components=circuit.components.filter(x=>x.id!==p.id);circuit.wires=circuit.wires.filter(w=>w.from.component!==p.id&&w.to.component!==p.id);selected=null;results=null;render();showProps();save();};
  }
  function showResults(){const host=$('#results-content');host.classList.remove('empty-instruments');host.innerHTML=`<div class="solve-summary"><span class="success-icon">✓</span><div><b>Circuit solved</b><small>${results.summary}</small></div></div><div class="reading-grid">${results.components.filter(r=>r.type!=='ground').map(r=>{const extra=r.inputCurrent!==undefined?`<div class="model-note">Input ${fmt(r.inputVoltage,' V')} · ${fmt(r.inputCurrent,' A')} · ${fmt(r.inputPower,' W')}</div>`:r.model?`<div class="model-note">${r.model}</div>`:'';return `<article class="reading-card"><div class="reading-top"><span class="reading-icon" style="--icon:${colors[r.type]}">${icons[r.type]}</span><span>${C.definitions[r.type].label} <small>${r.id}</small></span></div><div class="reading-primary">${fmt(r.voltage,' V')}</div><div class="reading-secondary"><span>Current <b>${fmt(r.current,' A')}</b></span><span>Power <b>${fmt(r.power,' W')}</b></span></div>${extra}</article>`;}).join('')}</div><div class="node-readings"><div class="eyebrow">NODE VOLTAGES</div>${Object.entries(results.nodes).map(([n,v])=>`<div><span>${n}</span><b>${fmt(v,' V')}</b></div>`).join('')||'<small>All terminals at ground potential.</small>'}</div>`;$('#run-time').textContent='SIMULATION COMPLETE';$('#status-text').textContent='Solved successfully';}
  function run(){try{results=C.solve(circuit);showResults();notify('Simulation converged successfully');}catch(e){results=null;$('#results-content').classList.add('empty-instruments');$('#results-content').innerHTML=`<div class="error-state"><span>!</span><b>Simulation stopped</b><p>${e.message}</p><small>Check the wiring and make sure each circuit has a ground.</small></div>`;$('#run-time').textContent='SIMULATION ERROR';$('#status-text').textContent='Needs attention';}}
  $('#run-btn').onclick=run;$('#new-btn').onclick=()=>{circuit=C.createCircuit('Untitled circuit');selected=null;results=null;placement=0;render();showProps();save();};$('#fit-btn').onclick=()=>notify('Schematic fits the workspace');$('#clear-wires').onclick=()=>{circuit.wires=[];results=null;render();save();notify('All wires cleared');};$('#mcp-copy').onclick=async()=>{try{await navigator.clipboard.writeText('node mcp-server.js');notify('MCP command copied');}catch{notify('Run “node mcp-server.js” from this project folder');}};
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();run();}if(e.key==='Escape'){wireStart=null;render();}if((e.key==='Delete'||e.key==='Backspace')&&selected&&!['INPUT'].includes(document.activeElement.tagName))$('#delete-part')?.click();});
  if(!circuit.components.length){circuit=C.createCircuit('Series circuit · 5V');circuit.name='Series circuit · 5V';const v=C.addComponent(circuit,'voltage',{x:260,y:270}),r=C.addComponent(circuit,'resistor',{x:500,y:270,resistance:1000}),g=C.addComponent(circuit,'ground',{x:740,y:385});C.connect(circuit,{component:v.id,terminal:'+'},{component:r.id,terminal:'a'});C.connect(circuit,{component:r.id,terminal:'b'},{component:g.id,terminal:'gnd'});C.connect(circuit,{component:v.id,terminal:'−'},{component:g.id,terminal:'gnd'});}
  render();showProps();save();
})();
